name: test

env:
  NODE_ENV: test
  DEVELOPMENT_TYPE: local
  FRONTEND_URL: http://localhost:3000
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  POSTGRES_HOST: localhost
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  REDIS_HOST: localhost
  REDIS_PASSWORD: fake-password
  REDIS_URL: redis://localhost:6379
  JWT_EXPIRES_IN_SECONDS: 60
  JWT_SECRET: fake-secret

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        env:
          REDIS_HOST: localhost
          REDIS_PASSWORD: fake-password
          REDIS_URL: redis://localhost:6379
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies and packages
        run: yarn install
      - name: Run migrations
        run: yarn migration:dev
      - name: Run database types generation
        run: yarn generate
      - name: Run the test Script
        run: yarn test